app:
  name: "user-microservice"
  environment: "development" 
  version: "1.0.0"

server:
  port: 8080
  readTimeout: "15s"
  writeTimeout: "15s"
  idleTimeout: "60s"

database:
  host: "localhost" 
  port: 5432
  sslmode: "disable"  

logging:
  level: "debug"

notification:
  queueName: "user_notifications"  